apiVersion: apps/v1
kind: Deployment
metadata:
  name: scanserver-deployment-kies
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scanserver-kies
  template:
    metadata:
      labels:
        app: scanserver-kies
    spec:
      containers:
      - env:
        - name: USERNAME
          value: kies
        - name: WEBSITE
          value: http://members.kaiyuanshe.cn/
        - name: RUNWAY
          value: cookie
        - name: USERCOOKIE1
          value: health-data-Id=MGQ0MTM0YmQtMWQ2NC00MGViLTkzMGMtODNkZDM4ODU3YjJi
        - name: USERCOOKIE2
          value: 1=1
        image: scanserver
        imagePullPolicy: IfNotPresent
        name: scanserver-kies
